### ISSUE TITLE
Day 01.2 In-memory Database

### ISSUE THREAD

**Issue by Jacobvu84** [Jacobvu84/developer-career#5]
- https://www.baeldung.com/spring-boot-h2-database

Let's begin with the [h2](https://search.maven.org/search?q=g:com.h2database%20a:h2) and [spring-boot-starter-data-jpa](https://search.maven.org/search?q=a:spring-boot-starter-data-jpa%20g:org.springframework.boot) dependencies:

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <scope>runtime</scope>
</dependency>
```

Database Configuration

By default, Spring Boot configures the application to connect to an in-memory store with the username sa and an empty password.

However, we can change those parameters by adding the following properties to the application.properties file:

> spring.datasource.url=jdbc:h2:mem:testdb
> spring.datasource.driverClassName=org.h2.Driver
> spring.datasource.username=sa
> spring.datasource.password=password
> spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

Alternatively, we can also use YAML for the database configuration of the application by adding the corresponding properties to the application.yaml file:

```
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
```

By design, **the in-memory database is volatile, and results in data loss after application restart.**

We can change that behavior by using file-based storage. To do this we need to update the spring.datasource.url property:

> spring.datasource.url=jdbc:h2:file:/data/demo

Similarly, In application.yaml, we can add the same property for file-based storage:

```
spring:
  datasource:
    url: jdbc:h2:file:/data/demo
```
